
const List<String> routeNames = <String>[
  'fluttercandies://CustomToolBar',
  'fluttercandies://NoKeyboard',
  'fluttercandies://SelectableTextDemo',
  'fluttercandies://TextDemo',
  'fluttercandies://WidgetSpanDemo',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();
  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
